name: core_ui

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  theme:
    path: ../theme
  utils:
    path: ../../packages/utils

  # State Management.
  provider: ^6.1.1

  # UI - Widgets.
  multi_split_view: ^2.4.0
  flash: ^3.0.5+2
  gradient_borders: ^1.0.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  context_menus:
    git:
      url: https://github.com/SoFluffyOS/flutter-context-menu.git
      ref: 4081ec557e2f581e40d34d3c6a70b9a23efcb1ef

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/arrows/bulk/
    - assets/icons/arrows/outline/
    - assets/icons/arrows/solid/
    - assets/icons/business/bulk/
    - assets/icons/business/outline/
    - assets/icons/business/solid/
    - assets/icons/communication/bulk/
    - assets/icons/communication/outline/
    - assets/icons/communication/solid/
    - assets/icons/device/bulk/
    - assets/icons/device/outline/
    - assets/icons/device/solid/
    - assets/icons/ecommerce/bulk/
    - assets/icons/ecommerce/outline/
    - assets/icons/ecommerce/solid/
    - assets/icons/editor/bulk/
    - assets/icons/editor/outline/
    - assets/icons/editor/solid/
    - assets/icons/education/bulk/
    - assets/icons/education/outline/
    - assets/icons/education/solid/
    - assets/icons/files and folder/bulk/
    - assets/icons/files and folder/outline/
    - assets/icons/files and folder/solid/
    - assets/icons/finance and payment/bulk/
    - assets/icons/finance and payment/outline/
    - assets/icons/finance and payment/solid/
    - assets/icons/grid/bulk/
    - assets/icons/grid/outline/
    - assets/icons/grid/solid/
    - assets/icons/health/bulk/
    - assets/icons/health/outline/
    - assets/icons/health/solid/
    - assets/icons/interface/bulk/
    - assets/icons/interface/outline/
    - assets/icons/interface/solid/
    - assets/icons/menu/bulk/
    - assets/icons/menu/outline/
    - assets/icons/menu/solid/
    - assets/icons/multimedia and audio/bulk/
    - assets/icons/multimedia and audio/outline/
    - assets/icons/multimedia and audio/solid/
    - assets/icons/navigation maps/bulk/
    - assets/icons/navigation maps/outline/
    - assets/icons/navigation maps/solid/
    - assets/icons/notes and task/bulk/
    - assets/icons/notes and task/outline/
    - assets/icons/notes and task/solid/
    - assets/icons/shipping and delivery/bulk/
    - assets/icons/shipping and delivery/outline/
    - assets/icons/shipping and delivery/solid/
    - assets/icons/smart house/bulk/
    - assets/icons/smart house/outline/
    - assets/icons/smart house/solid/
    - assets/icons/social/bulk/
    - assets/icons/social/outline/
    - assets/icons/social/solid/
    - assets/icons/time and date/bulk/
    - assets/icons/time and date/outline/
    - assets/icons/time and date/solid/
    - assets/icons/user/bulk/
    - assets/icons/user/outline/
    - assets/icons/user/solid/
    - assets/icons/weather/bulk/
    - assets/icons/weather/outline/
    - assets/icons/weather/solid/

flutter_gen:
  output: lib/constants/generated/
  line_length: 80
  integrations:
    flutter_svg: true
